// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk9vYUS4RmzCp7SVUQsazvJ85EUx0O5kY',
    appId: '1:1027887561205:web:3e0c5552082a7d105008bc',
    messagingSenderId: '1027887561205',
    projectId: 'tik-tok-arden-dev',
    authDomain: 'tik-tok-arden-dev.firebaseapp.com',
    storageBucket: 'tik-tok-arden-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ8AECpXSjOQhtPXkLr6iC1VW0-PHF4Zo',
    appId: '1:1027887561205:android:2707109cdb305a805008bc',
    messagingSenderId: '1027887561205',
    projectId: 'tik-tok-arden-dev',
    storageBucket: 'tik-tok-arden-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqaeFobSQdzK0dYK35AjNvTMAiy-RGw2Y',
    appId: '1:1027887561205:ios:d9dbb22fb770cdb55008bc',
    messagingSenderId: '1027887561205',
    projectId: 'tik-tok-arden-dev',
    storageBucket: 'tik-tok-arden-dev.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk9vYUS4RmzCp7SVUQsazvJ85EUx0O5kY',
    appId: '1:1027887561205:web:6223fd605745bf375008bc',
    messagingSenderId: '1027887561205',
    projectId: 'tik-tok-arden-dev',
    authDomain: 'tik-tok-arden-dev.firebaseapp.com',
    storageBucket: 'tik-tok-arden-dev.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqaeFobSQdzK0dYK35AjNvTMAiy-RGw2Y',
    appId: '1:1027887561205:ios:d9dbb22fb770cdb55008bc',
    messagingSenderId: '1027887561205',
    projectId: 'tik-tok-arden-dev',
    storageBucket: 'tik-tok-arden-dev.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

}